// CMS SEO - Sitemap Generator

export interface SitemapUrl {
    loc: string;
    lastmod?: string;
    changefreq?: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
    priority?: number;
}

export interface SitemapOptions {
    baseUrl: string;
    urls: SitemapUrl[];
}

// Generate XML sitemap
export function generateSitemap(options: SitemapOptions): string {
    const urlEntries = options.urls.map((url) => {
        const loc = url.loc.startsWith('http') ? url.loc : `${options.baseUrl}${url.loc}`;

        let entry = `  <url>\n    <loc>${escapeXml(loc)}</loc>`;

        if (url.lastmod) {
            entry += `\n    <lastmod>${url.lastmod}</lastmod>`;
        }

        if (url.changefreq) {
            entry += `\n    <changefreq>${url.changefreq}</changefreq>`;
        }

        if (url.priority !== undefined) {
            entry += `\n    <priority>${url.priority.toFixed(1)}</priority>`;
        }

        entry += '\n  </url>';
        return entry;
    });

    return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries.join('\n')}
</urlset>`;
}

// Generate sitemap index (for multiple sitemaps)
export function generateSitemapIndex(
    baseUrl: string,
    sitemaps: Array<{ loc: string; lastmod?: string }>
): string {
    const entries = sitemaps.map((sitemap) => {
        const loc = sitemap.loc.startsWith('http')
            ? sitemap.loc
            : `${baseUrl}${sitemap.loc}`;

        let entry = `  <sitemap>\n    <loc>${escapeXml(loc)}</loc>`;

        if (sitemap.lastmod) {
            entry += `\n    <lastmod>${sitemap.lastmod}</lastmod>`;
        }

        entry += '\n  </sitemap>';
        return entry;
    });

    return `<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.join('\n')}
</sitemapindex>`;
}

// Escape special XML characters
function escapeXml(str: string): string {
    return str
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&apos;');
}

// Build sitemap URLs from CMS pages
export function buildSitemapFromPages(
    baseUrl: string,
    clientSlug: string,
    pages: Array<{
        slug: string;
        updatedAt: string | Date;
        status: string;
    }>
): SitemapUrl[] {
    return pages
        .filter((page) => page.status === 'published')
        .map((page) => ({
            loc: `${baseUrl}/feed/${clientSlug}/${page.slug}`,
            lastmod: new Date(page.updatedAt).toISOString().split('T')[0],
            changefreq: 'weekly' as const,
            priority: 0.8,
        }));
}

// Generate robots.txt content
export function generateRobotsTxt(options: {
    baseUrl: string;
    clientSlug: string;
    customRules?: string;
    disallowPaths?: string[];
}): string {
    const { baseUrl, clientSlug, customRules, disallowPaths = [] } = options;

    let content = `# Robots.txt for ${clientSlug}
# Generated by Keyword-Ninja CMS

User-agent: *
Allow: /feed/${clientSlug}/
`;

    // Add disallow rules
    disallowPaths.forEach((path) => {
        content += `Disallow: ${path}\n`;
    });

    // Add sitemap reference
    content += `
Sitemap: ${baseUrl}/feed/${clientSlug}/sitemap.xml
`;

    // Add custom rules if provided
    if (customRules) {
        content += `\n# Custom Rules\n${customRules}\n`;
    }

    return content;
}
